### PR TITLE
Resources Updated - Kartik Kannapur Python Programs

### PR DESCRIPTION
**Pull request by KartikKannapur**

### CODE REVIEW

**Comment by rajathkmp** [comment]
@KartikKannapur Conflicts?

**Comment by KartikKannapur** [comment]
No conflicts. Just added the resource link. There is a change in the Python Version, but that shouldn't have much of an impact. 

Any other changes to the repo required?

**Comment by Goddur** [comment]
Sorry new to this format and did not mean to connect to you project? Need to locate youtube tutorial on how to use.

Date: Thu, 8 Oct 2015 08:39:11 -0700

**Comment by rajathkmp** [comment]
@KartikKannapur  Cannot Merge Pull Request until  the conflict is resolved. ( The python version is changed to 2.7.10 )

Suggestions are always welcome.

**Comment by KartikKannapur** [comment]
@rajathkumarmp I have changed the Python version to 2.7.10. Can you try merging it now ?

**Pull request closed without merging**
